# --- CONFIGURATION LOCALE (PROFIL LOCAL) ---

# URL sans aucun guillemet
DB_URL=jdbc:postgresql://dpg-d8k9d08g4nts73fr095g-a.oregon-postgres.render.com:5432/platmoi_db?sslmode=require

# Identifiants de connexion (remplace bien par ton vrai mot de passe)
DB_USERNAME=platmoi_db_user
DB_PASSWORD=U7gQ3gO6yO0YHlDBqdM1Job74zlCrow1

spring.jpa.show-sql=true