# URL pointant sur votre machine locale
spring.datasource.url=jdbc:postgresql://localhost:5432/platmoi_db
spring.datasource.username=postgres
spring.datasource.password=ngouye2001

# Affichage des requêtes SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true