# --- CONFIGURATION LOCALE (PROFIL LOCAL) ---

# URL de ta base Render avec le mode SSL obligatoire (Corrigé : sans guillemets)
DB_URL=jdbc:postgresql://dpg-d8k9d08g4nts73fr095g-a.oregon-postgres.render.com:5432/platmoi_db?sslmode=require

# Identifiants de connexion
DB_USERNAME=platmoi_db_user
DB_PASSWORD=U7gQ3gO6yO0YHlDBqdM1Job74zlCrow1

# Tu peux aussi forcer l'affichage des requêtes SQL en local pour déboguer
spring.jpa.show-sql=true